language: node_js

node_js:
    - "6"

sudo: required

services:
  - docker

env:
  DBUS_SESSION_BUS_ADDRESS=/dev/null

script:
  - npm run lint
  - npm run deps
  - npm run start &
  - sleep 10
  - npm run test
  - xvfb-run npm run test-e2e
  - pkill node
